export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "./header.scss";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <a href="/">
            <h2>コーディング課題</h2>
          </a>
        </header>
        {children}
      </body>
    </html>
  );
}
