export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <a href="/">
            <h1>コーディング課題</h1>
          </a>
        </header>
        {children}
      </body>
    </html>
  );
}
